--- #YAML:1.0
name:               Acme-Time-Baby
version:            2009082401
abstract:           Tell time little children can understand
author:
    - Abigail <acme-time-baby@abigail.be>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test:                 0
requires:
    perl:  5.006
resources:
    repository:  git://github.com/Abigail/acme--time--baby.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - Time
    - Clock
test_requires:
    Test::Pod:  1
